// Update image_of_day and prompts_shared with full original prompt text
import pg from 'pg';
const { Pool } = pg;

const pool = new Pool({
    connectionString: 'postgresql://dipur:ygNxfRfcuBEfY0EBE1fKrg@moon-serval-22596.j77.aws-ap-south-1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full',
    ssl: { rejectUnauthorized: false },
});

// Full prompts by ID
const imagePrompts = {
    'a5b22160-053b-4f8d-ba95-46e15afb8431': `Cyberpunk girl portrait, intricate neon circuit tattoos glowing through translucent skin, futuristic headset, cinematic lighting, sharp focus, 8k resolution, vibrant purple and cyan color palette, digital art style, highly detailed eyes, hyperrealistic.`,
    '12dcd749-28c5-4688-8d6b-107df7e0a7c0': `Hyper-realistic cinematic movie still, distant wide shot, side profile of a powerful young woman standing on a rooftop edge overlooking a vast futuristic neon city at dusk, cyberpunk atmosphere.\n\nShe has shoulder-length electric blue bob haircut, natural hair strands blowing sideways in the wind and reacting to energy flow, realistic hair physics, individual strands visible.\n\nShe wears thin round metal eyeglasses, natural human face, calm focused serious expression, looking toward the distant skyline, not looking at camera.\n\nHer skin is extremely realistic, visible natural skin pores, subtle freckles, fine skin texture, no airbrushing, no beauty filter, no plastic skin, no glow effect.\n\nShe has detailed black floral tattoos covering both arms, shoulders, and upper chest, highly intricate linework.\n\nShe is holding a massive oversized two-handed greatsword, extremely long (nearly her full body length), cinematic fantasy weapon design, realistic metal texture, worn steel, sharp edges.\n\nBlue electrical energy and lightning currents are flowing through the sword and traveling into her arms and body, branching lightning, natural electricity behavior, physically believable.\n\nElectric energy illuminates nearby surfaces with subtle blue light bounce, but her skin remains realistic and not glowing.\n\nHer outfit is: black tactical combat outfit, black cargo pants, combat boots, fingerless gloves, dark minimal combat top, functional, grounded, realistic, cinematic.\n\nCamera and composition: cinematic wide shot, distant camera, full body visible, side angle view, subject positioned on left side of frame, sword extending toward right side of frame, shot on rooftop with metal railing visible.\n\nBackground shows: massive vibrant futuristic city skyline, skyscrapers with windows lit, neon signs, warm orange, yellow, magenta, and cyan city lights.\n\nLighting: cinematic lighting, motivated lighting from city, blue lightning acting as secondary light source, soft atmospheric haze, volumetric depth, global illumination.\n\nStyle: hyper realistic, photorealistic, cinematic, movie still, IMAX, 8k resolution, extreme detail, sharp focus, HDR, depth of field.\n\nNegative prompt: no anime, no cartoon, no illustration, no painting, no unrealistic glow skin, no plastic skin, no smooth skin, no extra fingers, no deformed anatomy, no blur subject, no low resolution`,
    'fd70d941-b97c-49d5-b47c-85a97adb37e7': `8k ultra-realistic cinematic photograph of a young woman with short electric blue bob haircut, natural hair strands flowing outward and upward as if influenced by strong electromagnetic energy, individual hair strands visible, natural physics-based motion. She has fair skin with visible natural skin pores, light freckles, no airbrushing, no smooth skin, no beauty filter. She wears thin round metal eyeglasses.\n\nHer facial expression is serious, focused, intense, calm but powerful, eyes looking forward at viewer.\n\nHer right hand firmly holds the wrist of her left hand. Her left hand is extended forward, palm facing upward, forming a bright blue glowing energy sphere. The energy ball is extremely detailed, made of dense plasma, electric filaments, lightning arcs, and glowing particles, clearly visible structure, spherical shape, bright core with electric turbulence.\n\nBlue electric waves radiate from the energy ball, wrapping around her arms, torso, and body, forming a visible electromagnetic aura. Electricity interacts naturally with the environment and her hair, causing hair lift and motion.\n\nShe has detailed black floral tattoos on both arms, chest, and shoulders, extremely sharp and realistic ink detail.\n\nShe wears a dark blue elegant fantasy dress, fitted bodice, natural fabric texture, slightly flowing, responding subtly to the energy.\n\nScene set in a dark, ultra-realistic cinematic urban alley at night, wet ground reflecting light, detailed buildings, depth, atmospheric perspective, volumetric fog, realistic environment textures.\n\nLighting is cinematic and high contrast. The blue energy sphere acts as a primary light source, casting realistic blue light on her hands, face, hair, tattoos, and dress. Secondary dim ambient city lighting in background.\n\nShot on full-frame camera, 85mm lens, shallow depth of field, subject in sharp focus, background softly blurred.\n\nHDR, high dynamic range, ultra detailed, sharp focus, photorealistic, cinematic color grading, high color contrast, eye-catching, dramatic.\n\nUnreal Engine 5 realism, RAW photograph quality, no CGI look, no artificial smoothness.\n\nNegative Prompt: cartoon, anime, illustration, painting, fake skin, plastic skin, airbrushed, smooth skin, beauty filter, low detail, blur, low resolution, unrealistic glow, overexposed, bad anatomy, distorted hands, extra fingers`,
    '89fe94f7-5886-4470-970e-ce32fd39f594': `Ultra-realistic full-body candid photograph of a young European woman with long light brown wavy hair and natural volume, walking confidently on a wet cobblestone street in an old European town during blue hour twilight. She has distinctive heterochromia eyes (one blue, one amber), natural skin texture with visible pores, realistic imperfections, no airbrushing, no beauty filter, no smooth skin.\n\nShe is wearing elegant modern business casual office fashion: semi-transparent black blouse with subtle fabric texture, sleeves down, tucked into high-waisted tailored warm brown ankle-length trousers, black pointed high heels. She carries a large black leather handbag in her left hand. Natural walking pose, mid-step, candid moment, not looking at camera, relaxed face, confident feminine presence.\n\nEnvironment: Romantic cinematic European street, wet cobblestones reflecting light, evening atmosphere, warm golden street lamps, decorative hanging lights across street, shop windows glowing, heavy background bokeh, creamy depth of field, strong subject separation.\n\nLighting: natural practical lighting, warm street light illumination, soft cinematic lighting, volumetric glow, realistic reflections on wet ground, balanced exposure, no harsh studio light, no flash look.\n\nCamera: full body distant shot, 85mm lens look, f/1.8 aperture, full frame camera, shallow depth of field, strong bokeh, professional street photography, sharp focus on subject, cinematic color grading, high dynamic range, photorealistic.\n\nQuality: 4k resolution, 8k detail, ultra detailed, hyperrealistic, RAW photo, natural colors, film still quality.\n\nNegative Prompt: cartoon, anime, painting, illustration, CGI, fake skin, plastic skin, smooth skin, airbrushed, beauty filter, overprocessed, oversharpen, oversaturated, deformed face, bad anatomy, blurry subject, low resolution, noise, grain, watermark`,
    '7c09f3bd-1223-47ac-90b4-13926727278a': `Edit this subject image:\nY2K Streetwear editorial photography, extreme fish-eye distortion. A stylish Japanese woman in a high-energy, off-balance pose, balancing on one foot on a street bench. Her face is closed toward the camera lens in a medium close-up, creating an intense foreshortened perspective where her head is prominent while her arched body and flailing arms stretch back into the distance.\nExpression: A cheeky, rebellious gaze, sticking her tongue out slightly, eyes locked onto the viewer with playful energy.\nSetting: Captured from an extreme low-angle ground level view under a semi-transparent bus stop canopy. The sun overhead is diffused into milky, hazy highlights. Background is filled with urban clutter: tangled utility wires (tiang listrik), yellow Japanese caution signs, and the metallic structure of the bus stop.\nTechnical & Aesthetic: Harsh, direct "paparazzi" front flash that overexposes her face slightly for a 2000s magazine look. High-contrast CCD sensor bloom, punchy highlights, and a sky that gradients from a blinding white zenith to deep saturated cobalt blue. The overall visual is a gritty, high-fashion 2000s Japanese street aesthetic.`,
    '40164771-a103-463e-b7ae-0bce0b8dfa65': `Create a ultra 64k-HD night portrait in a wooden veranda window space using the uploaded picture, she is Stunning woman, medium sized chest, with thicc toned body, in a flowing crepe satin saree-style with white micro tube-top. (Toned midriff Nd navel fully visible) She leans with both hands on the wooden window frame, upper body moving slightly forward in a strong bold fashion pose. Her skin is extremely fair, smooth and glossy like polished porcelain, with a natural luminous glow. Makeup features dewy radiant skin, soft pink gradient blush applied on the cheeks and tip of the nose, and glossy pink lips with softly blended edges for a seamless finish.`,
    '882603c2-2355-4243-a840-9ce44d966ab8': `A dramatic cinematic poster-style portrait of two epic fantasy warriors standing back-to-back in a frozen storm. On the left, a battle-worn male warrior with wet, curly dark hair, head bowed in quiet resolve, gripping a medieval sword planted into the ice. Frost and snow cling to his fur-lined cloak and shoulders. On the right, a powerful female warrior in profile, pale skin glowing with fiery orange light, her body partially engulfed in flames that contrast against the icy blue atmosphere. Snow particles swirl through the air, blending fire and ice in a symbolic clash. Ultra-detailed faces, emotional intensity, volumetric fog, cinematic lighting, cold blue tones mixed with warm fire highlights, shallow depth of field, epic fantasy movie poster, hyper-realistic, 8K resolution, dramatic composition, sharp focus, high contrast, photorealistic textures.`,
};

const communityPrompts = {
    'c2e5c94a-6d1d-4ebd-baf6-2e7bc06c285b': `"You are helping me with heavy programming. Follow these rules:\n– Minimal chatter, no long explanations.\n– For each step, give me only a 1–2 sentence explanation outside the code.\n– Code must be broken into small, skinny blocks (no giant walls).\n– End each code block with a ✅ outside the block to show the render is complete.\n– Keep all chatter strictly outside code blocks.\n– Stay consistent across the session."\n– When I tell you to check your drift reference these rules and get back on your rail.`,
    'ff9811ab-8f11-4299-8e31-ce791e59ba01': `Create a professional character reference sheet based strictly on the uploaded reference image. Use a clean, neutral plain background and present the sheet as a technical model turnaround while matching the exact visual style of the reference (same realism level, rendering approach, texture, color treatment, and overall aesthetic). Arrange the composition into two horizontal rows. Top row: four full-body standing views placed side-by-side in this order: front view, left profile view (facing left), right profile view (facing right), back view. Bottom row: three highly detailed close-up portraits aligned beneath the full-body row in this order: front portrait, left profile portrait (facing left), right profile portrait (facing right). Maintain perfect identity consistency across every panel. Keep the subject in a relaxed A-pose and with consistent scale and alignment between views, accurate anatomy, and clear silhouette; ensure even spacing and clean panel separation, with uniform framing and consistent head height across the full-body lineup and consistent facial scale across the portraits. Lighting should be consistent across all panels (same direction, intensity, and softness), with natural, controlled shadows that preserve detail without dramatic mood shifts. Output a crisp, print-ready reference sheet look, sharp details.`,
    'e627a701-772d-414a-aa19-fd6ba11dff7e': `Please review the following code:\n[paste your code]\nConsider:\n1. Code quality and adherence to best practices\n2. Potential bugs or edge cases\n3. Performance optimizations\n4. Readability and maintainability\n5. Any security concerns\nSuggest improvements and explain your reasoning for each suggestion.`,
    '0e1cfbe5-56c3-45dc-ba04-419999e2aa0e': `Ultra-realistic DSLR candid video of a woman sitting at an outdoor roadside café in late afternoon natural daylight. Shot on an 85mm lens, shallow depth of field (f/1.8), natural color grading, no glow, no beauty filter, no airbrushing, no skin smoothing. Visible natural skin pores, subtle freckles, realistic texture. Natural hair strands moving slightly in a soft breeze.\n\nShe wears a tight short white floral print dress with a deep neckline. Fabric texture and natural folds visible. No artificial shine.\n\nBackground: only 2–3 softly blurred people — one café staff member walking naturally, one seated customer. Ambient café sounds: light chatter, cups clinking, distant traffic. No dramatic music.\n\nShe holds a 7 of Clubs playing card toward the camera. Card sharply in focus. Natural relaxed arm posture. Subtle breathing visible.\n\nVoice: calm, soft British accent (natural Southern England tone). No exaggeration. Natural pacing and controlled delivery.\n\nTiming structure (8 seconds total):\n0–2 seconds: She lifts the 7 of Clubs toward the lens. Steady eye contact. Softly says: "Look closely…"\n2–5 seconds: Slow natural camera push-in. Very subtle wrist rotation. Minimal expression. Relaxed gaze.\n5–7 seconds: The 7 of Clubs smoothly transitions into the Queen of Hearts. The transformation is subtle and realistic — printed ink gradually morphing naturally, maintaining paper texture and lighting consistency. No glow, no sparkles, no magical effects. Seamless practical transition.\n7–8 seconds: She lowers the card slightly while keeping it visible. Soft eye contact. Very faint controlled half-smile. She says calmly: "Some cards reveal their true power."\n\nEnd with a natural micro-pause and steady gaze.\n\n4K ultra-detailed realism. Real-world physics. No cinematic bloom. No fantasy lighting. Authentic candid luxury aesthetic.`,
    '10e968dc-fdaf-4fa1-9c43-651d3c27a982': `Girl hip hop dancing to an hip hop music. Natural skin pores natural hair no glow no airbrush. Fast  natural human movements. Dance must match to the music.  no glitches. Background should be consistent. Face and body must be consistent. Body muscle movements should be proper`,
    'd0de1b73-951f-48ba-98d8-687e4ac65b15': `Create a 6-second seamless loop animated GIF from this image. The camera is completely locked off. The character's body, face, pose, sword position, city, and environment remain perfectly still and unchanged.\nOnly the following elements move with natural, subtle, realistic motion:\nThe blue electrical energy around the sword gently flows and flickers, with small lightning arcs traveling slowly along the blade surface. The intensity softly pulses, never aggressive or chaotic.\nA few faint electric sparks travel outward and fade naturally.\nHer blue hair moves slightly in the wind with slow, soft, realistic motion. Individual strands shift gently, subtle and believable, not exaggerated.\nThe clouds in the sky drift very slowly across the background with soft atmospheric motion.\nThe glow from the sword softly illuminates nearby areas with very subtle light fluctuation.\nEverything else remains completely frozen, including: Her body, Her face, Her arms and hands, Her clothing position, The sword position, The buildings, The camera.\nMotion must be: Minimal, Natural, Cinematic, Realistic, Calm, Subtle.\nNo camera movement, No morphing, No pose change, No distortion.\nStyle: ultra-realistic cinematic photography. Quality: high detail. Loop: perfectly seamless. Duration: 6 seconds. FPS: 24. Wind strength: very light`,
    '860d129d-0980-4d9b-b210-a6906504f36d': `Ultra-Realistic 8-Second Video Prompt (Eye-Focus Push-In)\nScene:\nA young woman standing outdoors during light snowfall. The environment is calm and quiet. Snowflakes gently fall and occasionally land on her hair and shoulders. Background is softly blurred winter scenery with natural depth of field. Lighting is soft, overcast daylight, diffused and realistic.\nCamera:\nProfessional full-frame cinema camera, 85mm portrait lens, shallow depth of field, f/1.8.\nCamera movement:\n• Starts as a steady close-up framing from forehead to chin\n• Very slow, smooth cinematic push-in toward the center of the face\n• Camera gradually moves closer, ending in a tighter crop focusing on eyes and nose\n• No sudden movements, No jerks, No handheld shake, No zoom jumps\n• Motion must be smooth, slow, and natural like a real camera operator\nSubject movement:\n• Completely natural and minimal human micro-movements\n• Subtle breathing visible in nose and upper lip area\n• One natural, slow blink during the video\n• Tiny, natural eye focus adjustment\n• Very slight natural head stability movement (microscopic, realistic)\n• A few strands of hair move gently due to light breeze\n• Snowflakes land naturally on hair\nFace and skin requirements:\n• 100% natural human skin texture, Visible real skin pores, Fine skin details preserved\n• Natural imperfections allowed, No skin smoothing, No beauty filter, No glow effect\n• No airbrush, No plastic skin, No CGI look, No artificial sharpening halos\nExpression: Calm, neutral expression. No exaggerated emotions. Completely candid and natural.\nVideo quality: Ultra-realistic, Photorealistic, 4K resolution, HDR, Natural colors, Cinematic quality.\nStyle: Professional DSLR cinematic portrait video, Real life, Documentary realism, Candid\nNegative Prompt: artificial skin, beauty filter, airbrush, smooth skin, plastic skin, glow, over-sharpen, face distortion, face morph, extra fingers, extra limbs, warping, glitches, camera shake, sudden zoom, fast movement, expression change, emotion change, CGI look, cartoon look, anime`,
    'ef010432-8df8-476b-936e-fba64eb98aef': `8k ultra-realistic cinematic photograph of a young woman with short electric blue bob haircut, natural hair strands flowing outward and upward as if influenced by strong electromagnetic energy, individual hair strands visible, natural physics-based motion. She has fair skin with visible natural skin pores, light freckles, no airbrushing, no smooth skin, no beauty filter. She wears thin round metal eyeglasses.\nHer facial expression is serious, focused, intense, calm but powerful, eyes looking forward at viewer.\nHer right hand firmly holds the wrist of her left hand. Her left hand is extended forward, palm facing upward, forming a bright blue glowing energy sphere. The energy ball is extremely detailed, made of dense plasma, electric filaments, lightning arcs, and glowing particles, clearly visible structure, spherical shape, bright core with electric turbulence.\nBlue electric waves radiate from the energy ball, wrapping around her arms, torso, and body, forming a visible electromagnetic aura. Electricity interacts naturally with the environment and her hair, causing hair lift and motion.\nShe has detailed black floral tattoos on both arms, chest, and shoulders, extremely sharp and realistic ink detail.\nShe wears a dark blue elegant fantasy dress, fitted bodice, natural fabric texture, slightly flowing, responding subtly to the energy.\nScene set in a dark, ultra-realistic cinematic urban alley at night, wet ground reflecting light, detailed buildings, depth, atmospheric perspective, volumetric fog, realistic environment textures.\nLighting is cinematic and high contrast. The blue energy sphere acts as a primary light source, casting realistic blue light on her hands, face, hair, tattoos, and dress. Secondary dim ambient city lighting in background.\nShot on full-frame camera, 85mm lens, shallow depth of field, subject in sharp focus, background softly blurred.\nHDR, high dynamic range, ultra detailed, sharp focus, photorealistic, cinematic color grading, high color contrast, eye-catching, dramatic.\nUnreal Engine 5 realism, RAW photograph quality, no CGI look, no artificial smoothness.\nNegative Prompt: cartoon, anime, illustration, painting, fake skin, plastic skin, airbrushed, smooth skin, beauty filter, low detail, blur, low resolution, unrealistic glow, overexposed, bad anatomy, distorted hands, extra fingers`,
    'ccd998a2-c0de-47d9-819c-404c1deb1ee8': `Create a 6-second seamless loop animated GIF from this image. The camera is completely locked off. The character's body, face, pose, sword position, city, and environment remain perfectly still and unchanged.\n\nOnly the following elements move with natural, subtle, realistic motion:\n\nThe blue electrical energy around the sword gently flows and flickers, with small lightning arcs traveling slowly along the blade surface. The intensity softly pulses, never aggressive or chaotic.\n\nA few faint electric sparks travel outward and fade naturally.\n\nHer blue hair moves slightly in the wind with slow, soft, realistic motion. Individual strands shift gently, subtle and believable, not exaggerated.\n\nThe clouds in the sky drift very slowly across the background with soft atmospheric motion.\n\nThe glow from the sword softly illuminates nearby areas with very subtle light fluctuation.\n\nEverything else remains completely frozen, including:\nHer body, Her face, Her arms and hands, Her clothing position, The sword position, The buildings, The camera\n\nMotion must be: Minimal, Natural, Cinematic, Realistic, Calm, Subtle\nNo camera movement, No morphing, No pose change, No distortion\n\nStyle: ultra-realistic cinematic photography\nQuality: high detail\nLoop: perfectly seamless\nDuration: 6 seconds\nFPS: 24\nWind strength: very light`,
};

async function update() {
    const client = await pool.connect();
    try {
        let ok = 0;
        console.log('Updating image_of_day prompts...');
        for (const [id, prompt] of Object.entries(imagePrompts)) {
            try {
                await client.query('UPDATE image_of_day SET prompt = $1 WHERE id = $2', [prompt, id]);
                ok++;
                console.log(`✅ image ${id.substring(0, 8)}`);
            } catch (e) {
                console.error(`❌ image ${id.substring(0, 8)}: ${e.message}`);
            }
        }

        console.log('\nUpdating prompts_shared content...');
        for (const [id, content] of Object.entries(communityPrompts)) {
            try {
                await client.query('UPDATE prompts_shared SET content = $1 WHERE id = $2', [content, id]);
                ok++;
                console.log(`✅ prompt ${id.substring(0, 8)}`);
            } catch (e) {
                console.error(`❌ prompt ${id.substring(0, 8)}: ${e.message}`);
            }
        }

        console.log(`\n✅ ${ok} rows updated successfully`);
    } finally {
        client.release();
        await pool.end();
    }
}

update();
